name: Docker Image CI

on:
  workflow_dispatch:  # Enables "Run workflow" button
  push:
    branches:
      - main
    paths:
      - 'source/**'
      - '.github/workflows/docker-image.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'source/**'
      - '.github/workflows/docker-image.yml'

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set Docker image tag
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag achar007/python-app:${{ env.IMAGE_TAG }}

    - name: Push Docker image to Docker Hub
      run: docker push achar007/python-app:${{ env.IMAGE_TAG }}

  cd:
    runs-on: self-hosted
    needs: ci

    steps:
    - uses: actions/checkout@v4

    - name: Install Argocd
      shell: bash
      run: |
        curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
        sudo chmod +x argocd
        sudo mv ./argocd /usr/local/bin/argocd

    - name: Argocd app sync
      shell: bash
      run: |
        argocd login argocd-server.argocd \
        --insecure \
        --grpc-web \
        --username admin\
        --password ${{ secrets.ARGOCD_PASSWORD }}
        app sync argocd/python-app